### ISSUE TITLE
Twitch authorization failing on redirect it seems.

### ISSUE THREAD

**Issue by marnux** [s4my/TwitchLiveChannels#4]
When clicking on the authorize button in the authorization page of Twitch, i get an error on the redirect uri given for extensions.allizom.org.
We can’t connect to the server at ....extensions.allizom.org.
I'm not sure what the issue might be, but it seems like the uri just isn't valid.
Left the start of the uri off, as i don't know if it's unique to me or just general.

**Comment by s4my** [comment]
> When clicking on the authorize button in the authorization page of Twitch, i get an error on the redirect uri given for extensions.allizom.org. We can’t connect to the server at ....extensions.allizom.org. I'm not sure what the issue might be, but it seems like the uri just isn't valid. Left the start of the uri off, as i don't know if it's unique to me or just general.

hi @marnux, the URI is not unique to you, I just tested it and it works fine, I can't help you without more context, could you show me a screenshot of what happens, maybe you're having network issues. 
you can also open the following URL in firefox, and click on **console** tab on the top left and tell me what error messages you seeing.
URL: `about:devtools-toolbox?id=%7Bd3d2a327-1ae0-4fd6-b732-0844d0b7fd4c%7D&type=extension`

**Comment by marnux** [comment]
Sorry it took a bit of time, but was testing some things on my end.
Here are screenshots of what i see.
![twitch_auth](https://user-images.githubusercontent.com/33655142/164972699-8deba399-8be1-494d-ad89-cd8ff211629f.png)
![Twitch_failure](https://user-images.githubusercontent.com/33655142/164972701-9b392055-308d-4b9b-817e-475df1152aa3.png)
Might be an issue somewhere on my isp's side however, as i can't seem to do a successful traceroute to *.allizom.org. I get to my isp and then it fails to resolve further. I seem to have similar issues with other extensions.allizom.org using extension. Extensions that use a different uri seem to work fine.

**Comment by s4my** [comment]
hi @marnux, I might be able to help, you should copy the URL in the 2nd screenshot and show it to me, and please like I said in my 1st message, you should open this `about:devtools-toolbox?id=%7Bd3d2a327-1ae0-4fd6-b732-0844d0b7fd4c%7D&type=extension` in firefox (this will open the [dev tools](https://firefox-source-docs.mozilla.org/devtools-user/index.html) on the extension) then on the top left click on the [`Console`](https://firefox-source-docs.mozilla.org/devtools-user/index.html#web-console) tab and if there are any errors expand them and send me a screenshot of that.  
btw the *.allizom.org is a Mozilla domain generated automatically for extensions (read it backward and you'll see).

**Comment by marnux** [comment]
Here is the url, without my access token:
https://e094a0427d6f941f1445d8e7a3cbfad017240f47.extensions.allizom.org/#access_token=xxxxxxxxxxxxxxxxxxxxxx&scope=user%3Aread%3Afollows&token_type=bearer
The errors i see with the command are the following:
This error is listed 20+ times:
```
Error: could not find "loggedin" in storage.
    getStorageItem moz-extension://77be16e4-4624-4e10-9cac-0bb068b01ef1/background.js:63
    updateLiveChannels moz-extension://77be16e4-4624-4e10-9cac-0bb068b01ef1/background.js:185
```
This error is only listed once:
```
failed to get Access Token (redirect_url: undefined options.js
    logIn moz-extension://77be16e4-4624-4e10-9cac-0bb068b01ef1/options.js:46
```

**Comment by s4my** [comment]
hi @marnux, something is odd here, you got the right redirect URI, but something intercepted the request (maybe javascript got injected to the oauth page ?), I want you to **disable all extensions** but Twitch Live Channels (i mean everything, ad blockers, and everything..), and also **disable any VPN's or proxies** if you use any, then make sure you have installed the latest version of Twitch Live Channels (1.0.16), after that open `about:devtools-toolbox?id=%7Bd3d2a327-1ae0-4fd6-b732-0844d0b7fd4c%7D&type=extension` in firefox, on the top left click on the [Console](https://firefox-source-docs.mozilla.org/devtools-user/index.html#web-console) tab and if there are any errors send them back.
I hope this was helpful.

**Comment by marnux** [comment]
Disabling all extensions made it work, but now i can't figure out which one was causing it. If i log out, would i retrigger the whole authorization chain or would i need to revoke my authorization on twitch side? Then i can check which one is the cause of the behaviour. Disabling all is not handy, so it would be nice to pinpoint the exact problem. It seems however that once authorized, i can enable all of the extensions again. You can close this if you don't want to investigate further. I'll be checking out what extension is the root cause anyway, as i have similar issues with other extensions as well.

**Comment by s4my** [comment]
😉 am glad it solved the problem as i told you

> something intercepted the request (maybe javascript got injected to the oauth page ?)

And to answer your question, if you log out you don't need to revoke the authorization on the twitch side the extension handles that for you. and to find which extension is causing the problem try enabling them one by one, which you don't really need to do once you're logged in in the Twitch Live Channels, you can just do it for future reference if it causes you problem with other extensions.
With this, am closing this issue since it's not related to the extension, and don't forget to leave a [review](https://addons.mozilla.org/en-US/firefox/addon/twitch-live-channels/reviews/) and share it with your friends :)
