### ISSUE TITLE
Extension no longer shows all channel

### ISSUE THREAD

**Issue by Gwarion** [s4my/TwitchLiveChannels#8]
I don't know why recently the extension stopped full working and only shows me some streamers 

![image](https://github.com/s4my/TwitchLiveChannels/assets/41459318/d4e137ea-9f89-4d09-8711-fe3df1cc4e6e)

vs other extention

![image](https://github.com/s4my/TwitchLiveChannels/assets/41459318/9fefd883-1511-4872-ae50-2012ec50d8dc)

If you plan on fixing this and If you need any logs let me know

**Comment by s4my** [comment]
That is so weird. Can you try to fully reinstalling it, and disable all other extensions when you test it, maybe there's interference from another extension.

You can also check if there's any errors in the console by following these steps:
- Click on the _puzzle_ icon in the top right of Firefox
- Click on the _cog_ icon to open the menu and select **Debug Add-ons**
- Click on the **Inspect** button next *Twitch Live Channels* 
- On the newly opened Developer Tools window, click on the **Console** tab and check if there are any errors.

**Comment by Gwarion** [comment]
I installed the 2nd one when I noticed yours wasnt working properly anymore. I wanted to make sure it wasnt related to my twitch account settings. 

The difference I noticed are 

1. The request parameters are different in the uri : the other extension uses `followed?first=100&user_id=130314176`
2. The headers sent on the GET are different. The other extesion adds
    - cache-control: no-cache
    - cookie: json with a bunch of data (token / ids / etc)

I reinstalled your extension and now it doesnt load anything anymore. I have this error in the console

![image](https://github.com/s4my/TwitchLiveChannels/assets/41459318/baae0585-9a13-41db-8167-53c688376605)

**Comment by s4my** [comment]
> I reinstalled your extension and now it doesnt load anything anymore. I have this error in the console

Have you made sure to reconnect to your account in the settings?

> The request parameters are different in the uri : the other extension uses followed?first=100&user_id=130314176

The `first=100` just means the maximum number of items to return per page in the response (which I should set to 100 too since the default is 20 now).

> cache-control: no-cache

that disables cache, so maybe it's a caching issue with you. Can you try to `Disable cache` in the `Network` tab (in the Developer Tools that is). If you don't know how, let me help you.

**Comment by Gwarion** [comment]
oh I didnt save the login my bad. After reinsalling I now get all the chanel back. I wonder if it was a cache related issue. Ill let you know if I ever replicates the issue

**Comment by s4my** [comment]
> I wonder if it was a cache related issue.

@Gwarion I updated my comment by the time you responded. I believe it is. Thank you so much for reporting this issue :). Am glad it works now.

**Comment by s4my** [comment]
Fixed the issue in the new version [v1.0.18](https://github.com/s4my/TwitchLiveChannels/releases/tag/v1.0.18).

**Comment by s4my** [comment]
> oh I didnt save the login my bad.

I remove the save button completely in [v 1.0.19](https://github.com/s4my/TwitchLiveChannels/releases/tag/v1.0.19). Now settings are saved automatically, so this should never happen again.
